// spline_gen.ts -- AUTO-GENERATED by tools/emit-spline.js
// DO NOT HAND-EDIT.  Source of truth: exprforge/samples/spline-frame.js
// Regenerate: node tools/emit-spline.js
//
// Functions: SpEfMkFrame, SpEfActualPos, SpEfRollFrame, SpEfCrWeights,
//            SpEfCrDerivWeights, SpEfFacingNorm, SpEfArcAdvance

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfMkFrameResult {
    rx: number;
    ry: number;
    rz: number;
    ux: number;
    uy: number;
    uz: number;
}

export function SpEfMkFrame(tx: number, ty: number, tz: number): SpEfMkFrameResult {
    const mfWy = ((Math.abs(ty) > 0.98) ? 0 : 1);
    const mfWz = ((Math.abs(ty) > 0.98) ? 1 : 0);
    const mfCrossX = ((ty * mfWz) - (tz * mfWy));
    const mfCrossY = (0 - (tx * mfWz));
    const mfCrossZ = (tx * mfWy);
    const mfRLen = Math.sqrt((((mfCrossX * mfCrossX) + (mfCrossY * mfCrossY)) + (mfCrossZ * mfCrossZ)));
    const mfRxN = ((mfRLen > 0.000001) ? (mfCrossX / ((mfRLen > 0.000001) ? mfRLen : 1)) : 0);
    const mfRyN = ((mfRLen > 0.000001) ? (mfCrossY / ((mfRLen > 0.000001) ? mfRLen : 1)) : 0);
    const mfRzN = ((mfRLen > 0.000001) ? (mfCrossZ / ((mfRLen > 0.000001) ? mfRLen : 1)) : 1);
    return {
        rx: mfRxN,
        ry: mfRyN,
        rz: mfRzN,
        ux: ((mfRyN * tz) - (mfRzN * ty)),
        uy: ((mfRzN * tx) - (mfRxN * tz)),
        uz: ((mfRxN * ty) - (mfRyN * tx)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfActualPosResult {
    x: number;
    y: number;
    z: number;
}

export function SpEfActualPos(wx: number, wy_wire: number, wz_wire: number, tx: number, ty: number, tz: number, prDeg: number, so: number): SpEfActualPosResult {
    const apWy = ((Math.abs(ty) > 0.98) ? 0 : 1);
    const apWz = ((Math.abs(ty) > 0.98) ? 1 : 0);
    const apCrossX = ((ty * apWz) - (tz * apWy));
    const apCrossY = (0 - (tx * apWz));
    const apCrossZ = (tx * apWy);
    const apRLen = Math.sqrt((((apCrossX * apCrossX) + (apCrossY * apCrossY)) + (apCrossZ * apCrossZ)));
    const apRxN = ((apRLen > 0.000001) ? (apCrossX / ((apRLen > 0.000001) ? apRLen : 1)) : 0);
    const apRyN = ((apRLen > 0.000001) ? (apCrossY / ((apRLen > 0.000001) ? apRLen : 1)) : 0);
    const apRzN = ((apRLen > 0.000001) ? (apCrossZ / ((apRLen > 0.000001) ? apRLen : 1)) : 1);
    const apUx = ((apRyN * tz) - (apRzN * ty));
    const apUy = ((apRzN * tx) - (apRxN * tz));
    const apUz = ((apRxN * ty) - (apRyN * tx));
    const apRad = (prDeg * (3.141592653589793 / 180));
    const apC = Math.cos(apRad);
    const apS = Math.sin(apRad);
    return {
        x: (wx + (so * ((apC * apUx) + (apS * apRxN)))),
        y: (wy_wire + (so * ((apC * apUy) + (apS * apRyN)))),
        z: (wz_wire + (so * ((apC * apUz) + (apS * apRzN)))),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfRollFrameResult {
    rolledUx: number;
    rolledUy: number;
    rolledUz: number;
    rolledRx: number;
    rolledRy: number;
    rolledRz: number;
}

export function SpEfRollFrame(ux: number, uy: number, uz: number, rx: number, ry: number, rz: number, crDeg: number): SpEfRollFrameResult {
    const rfRad = (crDeg * (3.141592653589793 / 180));
    const rfC = Math.cos(rfRad);
    const rfS = Math.sin(rfRad);
    return {
        rolledUx: ((rfC * ux) - (rfS * rx)),
        rolledUy: ((rfC * uy) - (rfS * ry)),
        rolledUz: ((rfC * uz) - (rfS * rz)),
        rolledRx: ((rfS * ux) + (rfC * rx)),
        rolledRy: ((rfS * uy) + (rfC * ry)),
        rolledRz: ((rfS * uz) + (rfC * rz)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfCrWeightsResult {
    w0: number;
    w1: number;
    w2: number;
    w3: number;
}

export function SpEfCrWeights(t: number): SpEfCrWeightsResult {
    const cwT2 = (t * t);
    const cwT3 = (cwT2 * t);
    return {
        w0: (0.5 * (((0 - cwT3) + (2 * cwT2)) + (0 - t))),
        w1: (0.5 * (((3 * cwT3) + (-5 * cwT2)) + 2)),
        w2: (0.5 * (((-3 * cwT3) + (4 * cwT2)) + t)),
        w3: (0.5 * (cwT3 + (0 - cwT2))),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfCrDerivWeightsResult {
    dw0: number;
    dw1: number;
    dw2: number;
    dw3: number;
}

export function SpEfCrDerivWeights(t: number): SpEfCrDerivWeightsResult {
    const dwT2 = (t * t);
    return {
        dw0: (0.5 * (((-3 * dwT2) + (4 * t)) + -1)),
        dw1: (0.5 * ((9 * dwT2) + (-10 * t))),
        dw2: (0.5 * (((-9 * dwT2) + (8 * t)) + 1)),
        dw3: (0.5 * ((3 * dwT2) + (-2 * t))),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfFacingNormResult {
    fx: number;
    fy: number;
    fz: number;
}

export function SpEfFacingNorm(dx: number, dy: number, dz: number): SpEfFacingNormResult {
    const fnFLen = Math.sqrt((((dx * dx) + (dy * dy)) + (dz * dz)));
    return {
        fx: ((fnFLen > 0.000001) ? (dx / ((fnFLen > 0.000001) ? fnFLen : 1)) : 0),
        fy: ((fnFLen > 0.000001) ? (dy / ((fnFLen > 0.000001) ? fnFLen : 1)) : 1),
        fz: ((fnFLen > 0.000001) ? (dz / ((fnFLen > 0.000001) ? fnFLen : 1)) : 0),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfArcAdvanceResult {
    advance: number;
}

export function SpEfArcAdvance(tx: number, ty: number, tz: number, speed: number): SpEfArcAdvanceResult {
    const aaTanLen = Math.sqrt((((tx * tx) + (ty * ty)) + (tz * tz)));
    return {
        advance: ((aaTanLen > 0.000001) ? (speed / ((aaTanLen > 0.000001) ? aaTanLen : 1)) : speed),
    };
}

