' spline_path_gen.bi -- AUTO-GENERATED by tools/emit-spline.js
' DO NOT HAND-EDIT.  Source of truth: math/spline-frame.js
' Regenerate: node tools/emit-spline.js
'
' Functions: SpEfMkFrame, SpEfActualPos, SpEfRollFrame, SpEfCrWeights,
'            SpEfCrDerivWeights, SpEfFacingNorm, SpEfArcAdvance,
'            SpEfTransportFrame

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfMkFrame (tx AS DOUBLE, ty AS DOUBLE, tz AS DOUBLE, rx AS DOUBLE, ry AS DOUBLE, rz AS DOUBLE, ux AS DOUBLE, uy AS DOUBLE, uz AS DOUBLE)
    Dim mfWy AS DOUBLE : mfWy = ((-1# * 0#) * (ABS(ty) > 0.98#) + 1# * (1# + (ABS(ty) > 0.98#)))
    Dim mfWz AS DOUBLE : mfWz = ((-1# * 1#) * (ABS(ty) > 0.98#) + 0# * (1# + (ABS(ty) > 0.98#)))
    Dim mfCrossX AS DOUBLE : mfCrossX = ((ty * mfWz) - (tz * mfWy))
    Dim mfCrossY AS DOUBLE : mfCrossY = (0# - (tx * mfWz))
    Dim mfCrossZ AS DOUBLE : mfCrossZ = (tx * mfWy)
    Dim mfRLen AS DOUBLE : mfRLen = SQR((((mfCrossX * mfCrossX) + (mfCrossY * mfCrossY)) + (mfCrossZ * mfCrossZ)))
    Dim mfRxN AS DOUBLE : mfRxN = ((-1# * (mfCrossX / ((-1# * mfRLen) * (ABS(mfRLen) > 0.000001#) + 1# * (1# + (ABS(mfRLen) > 0.000001#))))) * (ABS(mfRLen) > 0.000001#) + 0# * (1# + (ABS(mfRLen) > 0.000001#)))
    Dim mfRyN AS DOUBLE : mfRyN = ((-1# * (mfCrossY / ((-1# * mfRLen) * (ABS(mfRLen) > 0.000001#) + 1# * (1# + (ABS(mfRLen) > 0.000001#))))) * (ABS(mfRLen) > 0.000001#) + 0# * (1# + (ABS(mfRLen) > 0.000001#)))
    Dim mfRzN AS DOUBLE : mfRzN = ((-1# * (mfCrossZ / ((-1# * mfRLen) * (ABS(mfRLen) > 0.000001#) + 1# * (1# + (ABS(mfRLen) > 0.000001#))))) * (ABS(mfRLen) > 0.000001#) + 1# * (1# + (ABS(mfRLen) > 0.000001#)))
    rx = mfRxN
    ry = mfRyN
    rz = mfRzN
    ux = ((mfRyN * tz) - (mfRzN * ty))
    uy = ((mfRzN * tx) - (mfRxN * tz))
    uz = ((mfRxN * ty) - (mfRyN * tx))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfActualPos (wx AS DOUBLE, wy_wire AS DOUBLE, wz_wire AS DOUBLE, tx AS DOUBLE, ty AS DOUBLE, tz AS DOUBLE, prDeg AS DOUBLE, so AS DOUBLE, x AS DOUBLE, y AS DOUBLE, z AS DOUBLE)
    Dim apWy AS DOUBLE : apWy = ((-1# * 0#) * (ABS(ty) > 0.98#) + 1# * (1# + (ABS(ty) > 0.98#)))
    Dim apWz AS DOUBLE : apWz = ((-1# * 1#) * (ABS(ty) > 0.98#) + 0# * (1# + (ABS(ty) > 0.98#)))
    Dim apCrossX AS DOUBLE : apCrossX = ((ty * apWz) - (tz * apWy))
    Dim apCrossY AS DOUBLE : apCrossY = (0# - (tx * apWz))
    Dim apCrossZ AS DOUBLE : apCrossZ = (tx * apWy)
    Dim apRLen AS DOUBLE : apRLen = SQR((((apCrossX * apCrossX) + (apCrossY * apCrossY)) + (apCrossZ * apCrossZ)))
    Dim apRxN AS DOUBLE : apRxN = ((-1# * (apCrossX / ((-1# * apRLen) * (ABS(apRLen) > 0.000001#) + 1# * (1# + (ABS(apRLen) > 0.000001#))))) * (ABS(apRLen) > 0.000001#) + 0# * (1# + (ABS(apRLen) > 0.000001#)))
    Dim apRyN AS DOUBLE : apRyN = ((-1# * (apCrossY / ((-1# * apRLen) * (ABS(apRLen) > 0.000001#) + 1# * (1# + (ABS(apRLen) > 0.000001#))))) * (ABS(apRLen) > 0.000001#) + 0# * (1# + (ABS(apRLen) > 0.000001#)))
    Dim apRzN AS DOUBLE : apRzN = ((-1# * (apCrossZ / ((-1# * apRLen) * (ABS(apRLen) > 0.000001#) + 1# * (1# + (ABS(apRLen) > 0.000001#))))) * (ABS(apRLen) > 0.000001#) + 1# * (1# + (ABS(apRLen) > 0.000001#)))
    Dim apUx AS DOUBLE : apUx = ((apRyN * tz) - (apRzN * ty))
    Dim apUy AS DOUBLE : apUy = ((apRzN * tx) - (apRxN * tz))
    Dim apUz AS DOUBLE : apUz = ((apRxN * ty) - (apRyN * tx))
    Dim apRad AS DOUBLE : apRad = (prDeg * (3.141592653589793# / 180#))
    Dim apC AS DOUBLE : apC = COS(apRad)
    Dim apS AS DOUBLE : apS = SIN(apRad)
    x = (wx + (so * ((apC * apUx) + (apS * apRxN))))
    y = (wy_wire + (so * ((apC * apUy) + (apS * apRyN))))
    z = (wz_wire + (so * ((apC * apUz) + (apS * apRzN))))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfRollFrame (ux AS DOUBLE, uy AS DOUBLE, uz AS DOUBLE, rx AS DOUBLE, ry AS DOUBLE, rz AS DOUBLE, crDeg AS DOUBLE, rolledUx AS DOUBLE, rolledUy AS DOUBLE, rolledUz AS DOUBLE, rolledRx AS DOUBLE, rolledRy AS DOUBLE, rolledRz AS DOUBLE)
    Dim rfRad AS DOUBLE : rfRad = (crDeg * (3.141592653589793# / 180#))
    Dim rfC AS DOUBLE : rfC = COS(rfRad)
    Dim rfS AS DOUBLE : rfS = SIN(rfRad)
    rolledUx = ((rfC * ux) - (rfS * rx))
    rolledUy = ((rfC * uy) - (rfS * ry))
    rolledUz = ((rfC * uz) - (rfS * rz))
    rolledRx = ((rfS * ux) + (rfC * rx))
    rolledRy = ((rfS * uy) + (rfC * ry))
    rolledRz = ((rfS * uz) + (rfC * rz))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfCrWeights (t AS DOUBLE, w0 AS DOUBLE, w1 AS DOUBLE, w2 AS DOUBLE, w3 AS DOUBLE)
    Dim cwT2 AS DOUBLE : cwT2 = (t * t)
    Dim cwT3 AS DOUBLE : cwT3 = (cwT2 * t)
    w0 = (0.5# * (((0# - cwT3) + (2# * cwT2)) + (0# - t)))
    w1 = (0.5# * (((3# * cwT3) + (-5# * cwT2)) + 2#))
    w2 = (0.5# * (((-3# * cwT3) + (4# * cwT2)) + t))
    w3 = (0.5# * (cwT3 + (0# - cwT2)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfCrDerivWeights (t AS DOUBLE, dw0 AS DOUBLE, dw1 AS DOUBLE, dw2 AS DOUBLE, dw3 AS DOUBLE)
    Dim dwT2 AS DOUBLE : dwT2 = (t * t)
    dw0 = (0.5# * (((-3# * dwT2) + (4# * t)) + -1#))
    dw1 = (0.5# * ((9# * dwT2) + (-10# * t)))
    dw2 = (0.5# * (((-9# * dwT2) + (8# * t)) + 1#))
    dw3 = (0.5# * ((3# * dwT2) + (-2# * t)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfFacingNorm (dx AS DOUBLE, dy AS DOUBLE, dz AS DOUBLE, fx AS DOUBLE, fy AS DOUBLE, fz AS DOUBLE)
    Dim __exprforgeMathNrmLen2 AS DOUBLE : __exprforgeMathNrmLen2 = SQR((((dx * dx) + (dy * dy)) + (dz * dz)))
    fx = ((-1# * (dx / ((-1# * __exprforgeMathNrmLen2) * (ABS(__exprforgeMathNrmLen2) > 0.000001#) + 1# * (1# + (ABS(__exprforgeMathNrmLen2) > 0.000001#))))) * (ABS(__exprforgeMathNrmLen2) > 0.000001#) + 0# * (1# + (ABS(__exprforgeMathNrmLen2) > 0.000001#)))
    fy = ((-1# * (dy / ((-1# * __exprforgeMathNrmLen2) * (ABS(__exprforgeMathNrmLen2) > 0.000001#) + 1# * (1# + (ABS(__exprforgeMathNrmLen2) > 0.000001#))))) * (ABS(__exprforgeMathNrmLen2) > 0.000001#) + 1# * (1# + (ABS(__exprforgeMathNrmLen2) > 0.000001#)))
    fz = ((-1# * (dz / ((-1# * __exprforgeMathNrmLen2) * (ABS(__exprforgeMathNrmLen2) > 0.000001#) + 1# * (1# + (ABS(__exprforgeMathNrmLen2) > 0.000001#))))) * (ABS(__exprforgeMathNrmLen2) > 0.000001#) + 0# * (1# + (ABS(__exprforgeMathNrmLen2) > 0.000001#)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfArcAdvance (tx AS DOUBLE, ty AS DOUBLE, tz AS DOUBLE, speed AS DOUBLE, advance AS DOUBLE)
    Dim aaTanLen AS DOUBLE : aaTanLen = SQR((((tx * tx) + (ty * ty)) + (tz * tz)))
    advance = ((-1# * (speed / ((-1# * aaTanLen) * (ABS(aaTanLen) > 0.000001#) + 1# * (1# + (ABS(aaTanLen) > 0.000001#))))) * (ABS(aaTanLen) > 0.000001#) + speed * (1# + (ABS(aaTanLen) > 0.000001#)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfTransportFrame (tx0 AS DOUBLE, ty0 AS DOUBLE, tz0 AS DOUBLE, tx1 AS DOUBLE, ty1 AS DOUBLE, tz1 AS DOUBLE, rx AS DOUBLE, ry AS DOUBLE, rz AS DOUBLE, ux AS DOUBLE, uy AS DOUBLE, uz AS DOUBLE, newRx AS DOUBLE, newRy AS DOUBLE, newRz AS DOUBLE, newUx AS DOUBLE, newUy AS DOUBLE, newUz AS DOUBLE)
    Dim tfBx AS DOUBLE : tfBx = ((ty0 * tz1) - (tz0 * ty1))
    Dim tfBy AS DOUBLE : tfBy = ((tz0 * tx1) - (tx0 * tz1))
    Dim tfBz AS DOUBLE : tfBz = ((tx0 * ty1) - (ty0 * tx1))
    Dim tfBLen AS DOUBLE : tfBLen = SQR((((tfBx * tfBx) + (tfBy * tfBy)) + (tfBz * tfBz)))
    Dim tfCosA AS DOUBLE : tfCosA = (((tx0 * tx1) + (ty0 * ty1)) + (tz0 * tz1))
    Dim tfKx AS DOUBLE : tfKx = ((-1# * (tfBx / ((-1# * tfBLen) * (ABS(tfBLen) > 0.000001#) + 1# * (1# + (ABS(tfBLen) > 0.000001#))))) * (ABS(tfBLen) > 0.000001#) + 0# * (1# + (ABS(tfBLen) > 0.000001#)))
    Dim tfKy AS DOUBLE : tfKy = ((-1# * (tfBy / ((-1# * tfBLen) * (ABS(tfBLen) > 0.000001#) + 1# * (1# + (ABS(tfBLen) > 0.000001#))))) * (ABS(tfBLen) > 0.000001#) + 0# * (1# + (ABS(tfBLen) > 0.000001#)))
    Dim tfKz AS DOUBLE : tfKz = ((-1# * (tfBz / ((-1# * tfBLen) * (ABS(tfBLen) > 0.000001#) + 1# * (1# + (ABS(tfBLen) > 0.000001#))))) * (ABS(tfBLen) > 0.000001#) + 1# * (1# + (ABS(tfBLen) > 0.000001#)))
    Dim tf1mC AS DOUBLE : tf1mC = (1# - tfCosA)
    Dim tfKdR AS DOUBLE : tfKdR = (((tfKx * rx) + (tfKy * ry)) + (tfKz * rz))
    Dim tfCKRx AS DOUBLE : tfCKRx = ((tfKy * rz) - (tfKz * ry))
    Dim tfCKRy AS DOUBLE : tfCKRy = ((tfKz * rx) - (tfKx * rz))
    Dim tfCKRz AS DOUBLE : tfCKRz = ((tfKx * ry) - (tfKy * rx))
    Dim tfKdU AS DOUBLE : tfKdU = (((tfKx * ux) + (tfKy * uy)) + (tfKz * uz))
    Dim tfCKUx AS DOUBLE : tfCKUx = ((tfKy * uz) - (tfKz * uy))
    Dim tfCKUy AS DOUBLE : tfCKUy = ((tfKz * ux) - (tfKx * uz))
    Dim tfCKUz AS DOUBLE : tfCKUz = ((tfKx * uy) - (tfKy * ux))
    newRx = ((-1# * (((rx * tfCosA) + (tfCKRx * tfBLen)) + (tfKx * (tfKdR * tf1mC)))) * (tfBLen > 0.000001#) + rx * (1# + (tfBLen > 0.000001#)))
    newRy = ((-1# * (((ry * tfCosA) + (tfCKRy * tfBLen)) + (tfKy * (tfKdR * tf1mC)))) * (tfBLen > 0.000001#) + ry * (1# + (tfBLen > 0.000001#)))
    newRz = ((-1# * (((rz * tfCosA) + (tfCKRz * tfBLen)) + (tfKz * (tfKdR * tf1mC)))) * (tfBLen > 0.000001#) + rz * (1# + (tfBLen > 0.000001#)))
    newUx = ((-1# * (((ux * tfCosA) + (tfCKUx * tfBLen)) + (tfKx * (tfKdU * tf1mC)))) * (tfBLen > 0.000001#) + ux * (1# + (tfBLen > 0.000001#)))
    newUy = ((-1# * (((uy * tfCosA) + (tfCKUy * tfBLen)) + (tfKy * (tfKdU * tf1mC)))) * (tfBLen > 0.000001#) + uy * (1# + (tfBLen > 0.000001#)))
    newUz = ((-1# * (((uz * tfCosA) + (tfCKUz * tfBLen)) + (tfKz * (tfKdU * tf1mC)))) * (tfBLen > 0.000001#) + uz * (1# + (tfBLen > 0.000001#)))
END SUB

