' spline_path_gen.bi -- AUTO-GENERATED by tools/emit-spline.js
' DO NOT HAND-EDIT.  Source of truth: math/spline-frame.js
' Regenerate: node tools/emit-spline.js
'
' Functions: SpEfMkFrame, SpEfActualPos, SpEfRollFrame, SpEfCrWeights,
'            SpEfCrDerivWeights, SpEfFacingNorm, SpEfArcAdvance

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfMkFrame (tx AS DOUBLE, ty AS DOUBLE, tz AS DOUBLE, rx AS DOUBLE, ry AS DOUBLE, rz AS DOUBLE, ux AS DOUBLE, uy AS DOUBLE, uz AS DOUBLE)
    Dim mfWy AS DOUBLE : mfWy = ((-1# * 0#) * (ABS(ty) > 0.98#) + 1# * (1# + (ABS(ty) > 0.98#)))
    Dim mfWz AS DOUBLE : mfWz = ((-1# * 1#) * (ABS(ty) > 0.98#) + 0# * (1# + (ABS(ty) > 0.98#)))
    Dim mfCrossX AS DOUBLE : mfCrossX = ((ty * mfWz) - (tz * mfWy))
    Dim mfCrossY AS DOUBLE : mfCrossY = (0# - (tx * mfWz))
    Dim mfCrossZ AS DOUBLE : mfCrossZ = (tx * mfWy)
    Dim mfRLen AS DOUBLE : mfRLen = SQR((((mfCrossX * mfCrossX) + (mfCrossY * mfCrossY)) + (mfCrossZ * mfCrossZ)))
    Dim mfRxN AS DOUBLE : mfRxN = ((-1# * (mfCrossX / ((-1# * mfRLen) * (mfRLen > 0.000001#) + 1# * (1# + (mfRLen > 0.000001#))))) * (mfRLen > 0.000001#) + 0# * (1# + (mfRLen > 0.000001#)))
    Dim mfRyN AS DOUBLE : mfRyN = ((-1# * (mfCrossY / ((-1# * mfRLen) * (mfRLen > 0.000001#) + 1# * (1# + (mfRLen > 0.000001#))))) * (mfRLen > 0.000001#) + 0# * (1# + (mfRLen > 0.000001#)))
    Dim mfRzN AS DOUBLE : mfRzN = ((-1# * (mfCrossZ / ((-1# * mfRLen) * (mfRLen > 0.000001#) + 1# * (1# + (mfRLen > 0.000001#))))) * (mfRLen > 0.000001#) + 1# * (1# + (mfRLen > 0.000001#)))
    rx = mfRxN
    ry = mfRyN
    rz = mfRzN
    ux = ((mfRyN * tz) - (mfRzN * ty))
    uy = ((mfRzN * tx) - (mfRxN * tz))
    uz = ((mfRxN * ty) - (mfRyN * tx))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfActualPos (wx AS DOUBLE, wy_wire AS DOUBLE, wz_wire AS DOUBLE, tx AS DOUBLE, ty AS DOUBLE, tz AS DOUBLE, prDeg AS DOUBLE, so AS DOUBLE, x AS DOUBLE, y AS DOUBLE, z AS DOUBLE)
    Dim apWy AS DOUBLE : apWy = ((-1# * 0#) * (ABS(ty) > 0.98#) + 1# * (1# + (ABS(ty) > 0.98#)))
    Dim apWz AS DOUBLE : apWz = ((-1# * 1#) * (ABS(ty) > 0.98#) + 0# * (1# + (ABS(ty) > 0.98#)))
    Dim apCrossX AS DOUBLE : apCrossX = ((ty * apWz) - (tz * apWy))
    Dim apCrossY AS DOUBLE : apCrossY = (0# - (tx * apWz))
    Dim apCrossZ AS DOUBLE : apCrossZ = (tx * apWy)
    Dim apRLen AS DOUBLE : apRLen = SQR((((apCrossX * apCrossX) + (apCrossY * apCrossY)) + (apCrossZ * apCrossZ)))
    Dim apRxN AS DOUBLE : apRxN = ((-1# * (apCrossX / ((-1# * apRLen) * (apRLen > 0.000001#) + 1# * (1# + (apRLen > 0.000001#))))) * (apRLen > 0.000001#) + 0# * (1# + (apRLen > 0.000001#)))
    Dim apRyN AS DOUBLE : apRyN = ((-1# * (apCrossY / ((-1# * apRLen) * (apRLen > 0.000001#) + 1# * (1# + (apRLen > 0.000001#))))) * (apRLen > 0.000001#) + 0# * (1# + (apRLen > 0.000001#)))
    Dim apRzN AS DOUBLE : apRzN = ((-1# * (apCrossZ / ((-1# * apRLen) * (apRLen > 0.000001#) + 1# * (1# + (apRLen > 0.000001#))))) * (apRLen > 0.000001#) + 1# * (1# + (apRLen > 0.000001#)))
    Dim apUx AS DOUBLE : apUx = ((apRyN * tz) - (apRzN * ty))
    Dim apUy AS DOUBLE : apUy = ((apRzN * tx) - (apRxN * tz))
    Dim apUz AS DOUBLE : apUz = ((apRxN * ty) - (apRyN * tx))
    Dim apRad AS DOUBLE : apRad = (prDeg * (3.141592653589793# / 180#))
    Dim apC AS DOUBLE : apC = COS(apRad)
    Dim apS AS DOUBLE : apS = SIN(apRad)
    x = (wx + (so * ((apC * apUx) + (apS * apRxN))))
    y = (wy_wire + (so * ((apC * apUy) + (apS * apRyN))))
    z = (wz_wire + (so * ((apC * apUz) + (apS * apRzN))))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfRollFrame (ux AS DOUBLE, uy AS DOUBLE, uz AS DOUBLE, rx AS DOUBLE, ry AS DOUBLE, rz AS DOUBLE, crDeg AS DOUBLE, rolledUx AS DOUBLE, rolledUy AS DOUBLE, rolledUz AS DOUBLE, rolledRx AS DOUBLE, rolledRy AS DOUBLE, rolledRz AS DOUBLE)
    Dim rfRad AS DOUBLE : rfRad = (crDeg * (3.141592653589793# / 180#))
    Dim rfC AS DOUBLE : rfC = COS(rfRad)
    Dim rfS AS DOUBLE : rfS = SIN(rfRad)
    rolledUx = ((rfC * ux) - (rfS * rx))
    rolledUy = ((rfC * uy) - (rfS * ry))
    rolledUz = ((rfC * uz) - (rfS * rz))
    rolledRx = ((rfS * ux) + (rfC * rx))
    rolledRy = ((rfS * uy) + (rfC * ry))
    rolledRz = ((rfS * uz) + (rfC * rz))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfCrWeights (t AS DOUBLE, w0 AS DOUBLE, w1 AS DOUBLE, w2 AS DOUBLE, w3 AS DOUBLE)
    Dim cwT2 AS DOUBLE : cwT2 = (t * t)
    Dim cwT3 AS DOUBLE : cwT3 = (cwT2 * t)
    w0 = (0.5# * (((0# - cwT3) + (2# * cwT2)) + (0# - t)))
    w1 = (0.5# * (((3# * cwT3) + (-5# * cwT2)) + 2#))
    w2 = (0.5# * (((-3# * cwT3) + (4# * cwT2)) + t))
    w3 = (0.5# * (cwT3 + (0# - cwT2)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfCrDerivWeights (t AS DOUBLE, dw0 AS DOUBLE, dw1 AS DOUBLE, dw2 AS DOUBLE, dw3 AS DOUBLE)
    Dim dwT2 AS DOUBLE : dwT2 = (t * t)
    dw0 = (0.5# * (((-3# * dwT2) + (4# * t)) + -1#))
    dw1 = (0.5# * ((9# * dwT2) + (-10# * t)))
    dw2 = (0.5# * (((-9# * dwT2) + (8# * t)) + 1#))
    dw3 = (0.5# * ((3# * dwT2) + (-2# * t)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfFacingNorm (dx AS DOUBLE, dy AS DOUBLE, dz AS DOUBLE, fx AS DOUBLE, fy AS DOUBLE, fz AS DOUBLE)
    Dim fnFLen AS DOUBLE : fnFLen = SQR((((dx * dx) + (dy * dy)) + (dz * dz)))
    fx = ((-1# * (dx / ((-1# * fnFLen) * (fnFLen > 0.000001#) + 1# * (1# + (fnFLen > 0.000001#))))) * (fnFLen > 0.000001#) + 0# * (1# + (fnFLen > 0.000001#)))
    fy = ((-1# * (dy / ((-1# * fnFLen) * (fnFLen > 0.000001#) + 1# * (1# + (fnFLen > 0.000001#))))) * (fnFLen > 0.000001#) + 1# * (1# + (fnFLen > 0.000001#)))
    fz = ((-1# * (dz / ((-1# * fnFLen) * (fnFLen > 0.000001#) + 1# * (1# + (fnFLen > 0.000001#))))) * (fnFLen > 0.000001#) + 0# * (1# + (fnFLen > 0.000001#)))
END SUB

' AUTO-GENERATED by ExprForge -- do not hand-edit.
SUB SpEfArcAdvance (tx AS DOUBLE, ty AS DOUBLE, tz AS DOUBLE, speed AS DOUBLE, advance AS DOUBLE)
    Dim aaTanLen AS DOUBLE : aaTanLen = SQR((((tx * tx) + (ty * ty)) + (tz * tz)))
    advance = ((-1# * (speed / ((-1# * aaTanLen) * (aaTanLen > 0.000001#) + 1# * (1# + (aaTanLen > 0.000001#))))) * (aaTanLen > 0.000001#) + speed * (1# + (aaTanLen > 0.000001#)))
END SUB

