// spline_gen.ts -- AUTO-GENERATED by tools/emit-spline.js
// DO NOT HAND-EDIT.  Source of truth: math/formula.expr
// Regenerate: node tools/emit-spline.js
//
// Functions: SpEfMkFrame, SpEfActualPos, SpEfRollFrame, SpEfCrWeights,
//            SpEfCrDerivWeights, SpEfFacingNorm, SpEfArcAdvance,
//            SpEfTransportFrame, SpEfFrustumAtX, SpEfApplyHolonomyCorrection,
//            SpEfMeasureHolonomy, SpEfYawPitch, SpEfRollFromFrame,
//            SpEfPhaseApproachRate, SpEfVelocityAttitude, SpEfHolonomyAngle,
//            SpEfHermiteTangentScale, SpEfHermitePos, SpEfHermiteTangent

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfMkFrameResult {
    rx: number;
    ry: number;
    rz: number;
    ux: number;
    uy: number;
    uz: number;
}

export function SpEfMkFrame(tx: number, ty: number, tz: number): SpEfMkFrameResult {
    const mfWy = ((Math.abs(ty) > 0.98) ? 0 : 1);
    const mfWz = ((Math.abs(ty) > 0.98) ? 1 : 0);
    const mfCrossX = ((ty * mfWz) - (tz * mfWy));
    const mfCrossY = (0 - (tx * mfWz));
    const mfCrossZ = (tx * mfWy);
    const mfRLen = Math.sqrt((((mfCrossX * mfCrossX) + (mfCrossY * mfCrossY)) + (mfCrossZ * mfCrossZ)));
    const mfRxN = ((Math.abs(mfRLen) > 0.000001) ? (mfCrossX / ((Math.abs(mfRLen) > 0.000001) ? mfRLen : 1)) : 0);
    const mfRyN = ((Math.abs(mfRLen) > 0.000001) ? (mfCrossY / ((Math.abs(mfRLen) > 0.000001) ? mfRLen : 1)) : 0);
    const mfRzN = ((Math.abs(mfRLen) > 0.000001) ? (mfCrossZ / ((Math.abs(mfRLen) > 0.000001) ? mfRLen : 1)) : 1);
    return {
        rx: mfRxN,
        ry: mfRyN,
        rz: mfRzN,
        ux: ((mfRyN * tz) - (mfRzN * ty)),
        uy: ((mfRzN * tx) - (mfRxN * tz)),
        uz: ((mfRxN * ty) - (mfRyN * tx)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfActualPosResult {
    x: number;
    y: number;
    z: number;
}

export function SpEfActualPos(wx: number, wy_wire: number, wz_wire: number, tx: number, ty: number, tz: number, prDeg: number, so: number): SpEfActualPosResult {
    const apWy = ((Math.abs(ty) > 0.98) ? 0 : 1);
    const apWz = ((Math.abs(ty) > 0.98) ? 1 : 0);
    const apCrossX = ((ty * apWz) - (tz * apWy));
    const apCrossY = (0 - (tx * apWz));
    const apCrossZ = (tx * apWy);
    const apRLen = Math.sqrt((((apCrossX * apCrossX) + (apCrossY * apCrossY)) + (apCrossZ * apCrossZ)));
    const apRxN = ((Math.abs(apRLen) > 0.000001) ? (apCrossX / ((Math.abs(apRLen) > 0.000001) ? apRLen : 1)) : 0);
    const apRyN = ((Math.abs(apRLen) > 0.000001) ? (apCrossY / ((Math.abs(apRLen) > 0.000001) ? apRLen : 1)) : 0);
    const apRzN = ((Math.abs(apRLen) > 0.000001) ? (apCrossZ / ((Math.abs(apRLen) > 0.000001) ? apRLen : 1)) : 1);
    const apUx = ((apRyN * tz) - (apRzN * ty));
    const apUy = ((apRzN * tx) - (apRxN * tz));
    const apUz = ((apRxN * ty) - (apRyN * tx));
    const apRad = (prDeg * (3.141592653589793 / 180));
    const apC = Math.cos(apRad);
    const apS = Math.sin(apRad);
    return {
        x: (wx + (so * ((apC * apUx) + (apS * apRxN)))),
        y: (wy_wire + (so * ((apC * apUy) + (apS * apRyN)))),
        z: (wz_wire + (so * ((apC * apUz) + (apS * apRzN)))),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfRollFrameResult {
    rolledUx: number;
    rolledUy: number;
    rolledUz: number;
    rolledRx: number;
    rolledRy: number;
    rolledRz: number;
}

export function SpEfRollFrame(ux: number, uy: number, uz: number, rx: number, ry: number, rz: number, crDeg: number): SpEfRollFrameResult {
    const rfRad = (crDeg * (3.141592653589793 / 180));
    const rfC = Math.cos(rfRad);
    const rfS = Math.sin(rfRad);
    return {
        rolledUx: ((rfC * ux) + (rfS * rx)),
        rolledUy: ((rfC * uy) + (rfS * ry)),
        rolledUz: ((rfC * uz) + (rfS * rz)),
        rolledRx: (((0 - rfS) * ux) + (rfC * rx)),
        rolledRy: (((0 - rfS) * uy) + (rfC * ry)),
        rolledRz: (((0 - rfS) * uz) + (rfC * rz)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfCrWeightsResult {
    w0: number;
    w1: number;
    w2: number;
    w3: number;
}

export function SpEfCrWeights(t: number): SpEfCrWeightsResult {
    const cwT2 = (t * t);
    const cwT3 = (cwT2 * t);
    return {
        w0: (0.5 * (((0 - cwT3) + (2 * cwT2)) - t)),
        w1: (0.5 * (((3 * cwT3) - (5 * cwT2)) + 2)),
        w2: (0.5 * ((((0 - 3) * cwT3) + (4 * cwT2)) + t)),
        w3: (0.5 * (cwT3 - cwT2)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfCrDerivWeightsResult {
    dw0: number;
    dw1: number;
    dw2: number;
    dw3: number;
}

export function SpEfCrDerivWeights(t: number): SpEfCrDerivWeightsResult {
    const dwT2 = (t * t);
    return {
        dw0: (0.5 * ((((0 - 3) * dwT2) + (4 * t)) - 1)),
        dw1: (0.5 * ((9 * dwT2) - (10 * t))),
        dw2: (0.5 * ((((0 - 9) * dwT2) + (8 * t)) + 1)),
        dw3: (0.5 * ((3 * dwT2) - (2 * t))),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfFacingNormResult {
    fx: number;
    fy: number;
    fz: number;
}

export function SpEfFacingNorm(dx: number, dy: number, dz: number): SpEfFacingNormResult {
    const efMathNrmLen2 = Math.sqrt((((dx * dx) + (dy * dy)) + (dz * dz)));
    const fnNorm__x = ((Math.abs(efMathNrmLen2) > 0.000001) ? (dx / ((Math.abs(efMathNrmLen2) > 0.000001) ? efMathNrmLen2 : 1)) : 0);
    const fnNorm__y = ((Math.abs(efMathNrmLen2) > 0.000001) ? (dy / ((Math.abs(efMathNrmLen2) > 0.000001) ? efMathNrmLen2 : 1)) : 1);
    const fnNorm__z = ((Math.abs(efMathNrmLen2) > 0.000001) ? (dz / ((Math.abs(efMathNrmLen2) > 0.000001) ? efMathNrmLen2 : 1)) : 0);
    return {
        fx: fnNorm__x,
        fy: fnNorm__y,
        fz: fnNorm__z,
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfArcAdvanceResult {
    advance: number;
}

export function SpEfArcAdvance(tx: number, ty: number, tz: number, speed: number): SpEfArcAdvanceResult {
    const aaTanLen = Math.sqrt((((tx * tx) + (ty * ty)) + (tz * tz)));
    return {
        advance: ((Math.abs(aaTanLen) > 0.000001) ? (speed / ((Math.abs(aaTanLen) > 0.000001) ? aaTanLen : 1)) : speed),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfTransportFrameResult {
    newRx: number;
    newRy: number;
    newRz: number;
    newUx: number;
    newUy: number;
    newUz: number;
}

export function SpEfTransportFrame(tx0: number, ty0: number, tz0: number, tx1: number, ty1: number, tz1: number, rx: number, ry: number, rz: number, ux: number, uy: number, uz: number): SpEfTransportFrameResult {
    const tfB__x = ((ty0 * tz1) - (tz0 * ty1));
    const tfB__y = ((tz0 * tx1) - (tx0 * tz1));
    const tfB__z = ((tx0 * ty1) - (ty0 * tx1));
    const tfBx = tfB__x;
    const tfBy = tfB__y;
    const tfBz = tfB__z;
    const tfBLen = Math.sqrt((((tfBx * tfBx) + (tfBy * tfBy)) + (tfBz * tfBz)));
    const tfCosA = (((tx0 * tx1) + (ty0 * ty1)) + (tz0 * tz1));
    const tfKx = ((Math.abs(tfBLen) > 0.000001) ? (tfBx / ((Math.abs(tfBLen) > 0.000001) ? tfBLen : 1)) : 0);
    const tfKy = ((Math.abs(tfBLen) > 0.000001) ? (tfBy / ((Math.abs(tfBLen) > 0.000001) ? tfBLen : 1)) : 0);
    const tfKz = ((Math.abs(tfBLen) > 0.000001) ? (tfBz / ((Math.abs(tfBLen) > 0.000001) ? tfBLen : 1)) : 1);
    const tf1mC = (1 - tfCosA);
    const tfKdR = (((tfKx * rx) + (tfKy * ry)) + (tfKz * rz));
    const kXr__x = ((tfKy * rz) - (tfKz * ry));
    const kXr__y = ((tfKz * rx) - (tfKx * rz));
    const kXr__z = ((tfKx * ry) - (tfKy * rx));
    const tfCKRx = kXr__x;
    const tfCKRy = kXr__y;
    const tfCKRz = kXr__z;
    const tfKdU = (((tfKx * ux) + (tfKy * uy)) + (tfKz * uz));
    const kXu__x = ((tfKy * uz) - (tfKz * uy));
    const kXu__y = ((tfKz * ux) - (tfKx * uz));
    const kXu__z = ((tfKx * uy) - (tfKy * ux));
    const tfCKUx = kXu__x;
    const tfCKUy = kXu__y;
    const tfCKUz = kXu__z;
    return {
        newRx: ((tfBLen > 0.000001) ? (((rx * tfCosA) + (tfCKRx * tfBLen)) + ((tfKx * tfKdR) * tf1mC)) : rx),
        newRy: ((tfBLen > 0.000001) ? (((ry * tfCosA) + (tfCKRy * tfBLen)) + ((tfKy * tfKdR) * tf1mC)) : ry),
        newRz: ((tfBLen > 0.000001) ? (((rz * tfCosA) + (tfCKRz * tfBLen)) + ((tfKz * tfKdR) * tf1mC)) : rz),
        newUx: ((tfBLen > 0.000001) ? (((ux * tfCosA) + (tfCKUx * tfBLen)) + ((tfKx * tfKdU) * tf1mC)) : ux),
        newUy: ((tfBLen > 0.000001) ? (((uy * tfCosA) + (tfCKUy * tfBLen)) + ((tfKy * tfKdU) * tf1mC)) : uy),
        newUz: ((tfBLen > 0.000001) ? (((uz * tfCosA) + (tfCKUz * tfBLen)) + ((tfKz * tfKdU) * tf1mC)) : uz),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfFrustumAtXResult {
    halfY: number;
    halfZ: number;
}

export function SpEfFrustumAtX(atX: number, camX: number, tanHfov: number, aspect: number): SpEfFrustumAtXResult {
    const frDist = (atX - camX);
    return {
        halfY: (frDist * tanHfov),
        halfZ: ((frDist * tanHfov) * aspect),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfApplyHolonomyCorrectionResult {
    corrRx: number;
    corrRy: number;
    corrRz: number;
    corrUx: number;
    corrUy: number;
    corrUz: number;
}

export function SpEfApplyHolonomyCorrection(rx: number, ry: number, rz: number, ux: number, uy: number, uz: number, holonomy: number, dArcFrac: number): SpEfApplyHolonomyCorrectionResult {
    const hcAngle = (0 - (holonomy * dArcFrac));
    const hcC = Math.cos(hcAngle);
    const hcS = Math.sin(hcAngle);
    return {
        corrRx: ((hcC * rx) + (hcS * ux)),
        corrRy: ((hcC * ry) + (hcS * uy)),
        corrRz: ((hcC * rz) + (hcS * uz)),
        corrUx: (((0 - hcS) * rx) + (hcC * ux)),
        corrUy: (((0 - hcS) * ry) + (hcC * uy)),
        corrUz: (((0 - hcS) * rz) + (hcC * uz)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfMeasureHolonomyResult {
    dotRR: number;
    dotRU: number;
}

export function SpEfMeasureHolonomy(finalRx: number, finalRy: number, finalRz: number, r0x: number, r0y: number, r0z: number, u0x: number, u0y: number, u0z: number): SpEfMeasureHolonomyResult {
    return {
        dotRR: (((finalRx * r0x) + (finalRy * r0y)) + (finalRz * r0z)),
        dotRU: (((finalRx * u0x) + (finalRy * u0y)) + (finalRz * u0z)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfYawPitchResult {
    yaw: number;
    pitch: number;
    horizLen: number;
}

export function SpEfYawPitch(dx: number, dy: number, dz: number): SpEfYawPitchResult {
    const ypHoriz = Math.sqrt(((dx * dx) + (dz * dz)));
    return {
        yaw: (Math.atan2(dz, (0 - dx)) * (180 / 3.141592653589793)),
        pitch: (Math.atan2((0 - dy), ypHoriz) * (180 / 3.141592653589793)),
        horizLen: ypHoriz,
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfRollFromFrameResult {
    roll: number;
}

export function SpEfRollFromFrame(ry: number, uy: number): SpEfRollFromFrameResult {
    return {
        roll: (Math.atan2(ry, uy) * (180 / 3.141592653589793)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfPhaseApproachRateResult {
    rate: number;
}

export function SpEfPhaseApproachRate(baseVx: number, phase: number): SpEfPhaseApproachRateResult {
    return {
        rate: (baseVx * (1 + ((phase - 1) * 0.4))),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfVelocityAttitudeResult {
    rx: number;
    ry: number;
    rz: number;
}

export function SpEfVelocityAttitude(vx: number, vy: number, vz: number): SpEfVelocityAttitudeResult {
    const vaRxRaw = ((vz * 90) - (vx * 15));
    const vaRyRaw = (0 - (vz * 35));
    const vaRzRaw = (vy * 60);
    return {
        rx: ((vaRxRaw > 70) ? 70 : ((vaRxRaw < (0 - 70)) ? (0 - 70) : vaRxRaw)),
        ry: ((vaRyRaw > 28) ? 28 : ((vaRyRaw < (0 - 28)) ? (0 - 28) : vaRyRaw)),
        rz: ((vaRzRaw > 50) ? 50 : ((vaRzRaw < (0 - 50)) ? (0 - 50) : vaRzRaw)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfHolonomyAngleResult {
    angle: number;
}

export function SpEfHolonomyAngle(dotRR: number, dotRU: number): SpEfHolonomyAngleResult {
    return {
        angle: Math.atan2(dotRU, dotRR),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfHermiteTangentScaleResult {
    m0x: number;
    m0y: number;
    m0z: number;
    m1x: number;
    m1y: number;
    m1z: number;
}

export function SpEfHermiteTangentScale(p0x: number, p0y: number, p0z: number, t0x: number, t0y: number, t0z: number, p1x: number, p1y: number, p1z: number, t1x: number, t1y: number, t1z: number): SpEfHermiteTangentScaleResult {
    const hsDx = (p1x - p0x);
    const hsDy = (p1y - p0y);
    const hsDz = (p1z - p0z);
    const hsDist = Math.sqrt((((hsDx * hsDx) + (hsDy * hsDy)) + (hsDz * hsDz)));
    const hsT0Len = Math.sqrt((((t0x * t0x) + (t0y * t0y)) + (t0z * t0z)));
    const hsT0xN = ((Math.abs(hsT0Len) > 0.000001) ? (t0x / ((Math.abs(hsT0Len) > 0.000001) ? hsT0Len : 1)) : (0 - 1));
    const hsT0yN = ((Math.abs(hsT0Len) > 0.000001) ? (t0y / ((Math.abs(hsT0Len) > 0.000001) ? hsT0Len : 1)) : 0);
    const hsT0zN = ((Math.abs(hsT0Len) > 0.000001) ? (t0z / ((Math.abs(hsT0Len) > 0.000001) ? hsT0Len : 1)) : 0);
    const hsT1Len = Math.sqrt((((t1x * t1x) + (t1y * t1y)) + (t1z * t1z)));
    const hsT1xN = ((Math.abs(hsT1Len) > 0.000001) ? (t1x / ((Math.abs(hsT1Len) > 0.000001) ? hsT1Len : 1)) : (0 - 1));
    const hsT1yN = ((Math.abs(hsT1Len) > 0.000001) ? (t1y / ((Math.abs(hsT1Len) > 0.000001) ? hsT1Len : 1)) : 0);
    const hsT1zN = ((Math.abs(hsT1Len) > 0.000001) ? (t1z / ((Math.abs(hsT1Len) > 0.000001) ? hsT1Len : 1)) : 0);
    return {
        m0x: (hsT0xN * hsDist),
        m0y: (hsT0yN * hsDist),
        m0z: (hsT0zN * hsDist),
        m1x: (hsT1xN * hsDist),
        m1y: (hsT1yN * hsDist),
        m1z: (hsT1zN * hsDist),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfHermitePosResult {
    x: number;
    y: number;
    z: number;
}

export function SpEfHermitePos(p0x: number, p0y: number, p0z: number, m0x: number, m0y: number, m0z: number, p1x: number, p1y: number, p1z: number, m1x: number, m1y: number, m1z: number, t: number): SpEfHermitePosResult {
    const hpT2 = (t * t);
    const hpT3 = (hpT2 * t);
    const hpH00 = (((2 * hpT3) - (3 * hpT2)) + 1);
    const hpH10 = ((hpT3 - (2 * hpT2)) + t);
    const hpH01 = (((0 - 2) * hpT3) + (3 * hpT2));
    const hpH11 = (hpT3 - hpT2);
    return {
        x: ((((hpH00 * p0x) + (hpH10 * m0x)) + (hpH01 * p1x)) + (hpH11 * m1x)),
        y: ((((hpH00 * p0y) + (hpH10 * m0y)) + (hpH01 * p1y)) + (hpH11 * m1y)),
        z: ((((hpH00 * p0z) + (hpH10 * m0z)) + (hpH01 * p1z)) + (hpH11 * m1z)),
    };
}

// AUTO-GENERATED by ExprForge — do not hand-edit.
export interface SpEfHermiteTangentResult {
    dx: number;
    dy: number;
    dz: number;
}

export function SpEfHermiteTangent(p0x: number, p0y: number, p0z: number, m0x: number, m0y: number, m0z: number, p1x: number, p1y: number, p1z: number, m1x: number, m1y: number, m1z: number, t: number): SpEfHermiteTangentResult {
    const htT2 = (t * t);
    const htDh00 = ((6 * htT2) - (6 * t));
    const htDh10 = (((3 * htT2) - (4 * t)) + 1);
    const htDh01 = (((0 - 6) * htT2) + (6 * t));
    const htDh11 = ((3 * htT2) - (2 * t));
    return {
        dx: ((((htDh00 * p0x) + (htDh10 * m0x)) + (htDh01 * p1x)) + (htDh11 * m1x)),
        dy: ((((htDh00 * p0y) + (htDh10 * m0y)) + (htDh01 * p1y)) + (htDh11 * m1y)),
        dz: ((((htDh00 * p0z) + (htDh10 * m0z)) + (htDh01 * p1z)) + (htDh11 * m1z)),
    };
}

