#!/bin/bash
# bake_speech_dict.sh — extract CMU phoneme entries needed for SSS game speech
# Run from repo root: bash 3d/tools/bake_speech_dict.sh
set -e

DICT="3d/assets/cmudict-0.txt"
OUT="3d/assets/speech_dict.txt"
TMP="$(mktemp)"

# ---- collect all unique words from game text and names ----
{
  # gametext.txt: strip block tags, color codes, template vars; pull words
  sed 's/{{[^}]*}}/ /g; s/\[BLOCK:[^]]*\]//g; s/~[0-9A-Fa-f][^ ]*//g' \
      3d/assets/gametext.txt | tr -cs 'A-Za-z' '\n' | tr 'a-z' 'A-Z'

  # gamevalues.ini: expand named vars (emperor, planets, resistance, etc.)
  grep -E '^(emperor|resistance|planet[1-9]|emperor_homeworld)' \
      3d/assets/gamevalues.ini | cut -d= -f2- | tr -cs 'A-Za-z' '\n' | tr 'a-z' 'A-Z'

  # hardcoded in-game phrases
  printf '%s\n' \
    "WARNING SHIELD CRITICAL BOSS INCOMING STAGE CLEAR" \
    "CHAPTER ONE TWO THREE FOUR FIVE SIX" \
    "PROLOGUE EPILOGUE GAME OVER" \
    "HELLO WORLD" | tr ' ' '\n'
} | sort -u | grep -v '^$' > "$TMP"

total=$(wc -l < "$TMP")

# ---- extract matching entries from CMU dict ----
{
  printf '# SSS speech phoneme dictionary\n'
  printf '# Generated by bake_speech_dict.sh  (%s)\n' "$(date -u '+%Y-%m-%d')"
  printf '\n'

  found=0
  while IFS= read -r word; do
    # Match "WORD " prefix (not WORD(2) alternate pronunciations)
    entry=$(grep "^${word} " "$DICT" | head -1)
    if [ -n "$entry" ]; then
      phones="${entry#* }"    # strip leading word
      printf '%s %s\n' "$word" "$phones"
      found=$((found + 1))
    fi
  done < "$TMP"

  printf '\n# %d / %d words found in CMU dict\n' "$found" "$total"
} > "$OUT"

rm -f "$TMP"
echo "Wrote $OUT  ($(grep -vc '^#\|^$' "$OUT") entries)"
