#!/usr/bin/env node
// emit-spline.js -- generate QB64 and TypeScript spline math from exprforge DSL.
//
// SINGLE SOURCE OF TRUTH: all flight-path math lives in exprforge ASTs.
// Run this script whenever the math changes. Generated files are committed;
// never hand-edit spline_path_gen.bi or spline_gen.ts.
//
// Usage:  node tools/emit-spline.js
//         (run from the 3d/ repo root)

'use strict';

const fs   = require('fs');
const path = require('path');

// Load emitAll from exprforge (installed in math/node_modules).
const { emitAll } = require('../math/node_modules/exprforge');

// All spline math ASTs live here — pure JS DSL, no QB64, no TypeScript.
const { splineFrameAsts } = require('../math/spline-frame.js');

const REPO = path.resolve(__dirname, '..');   // 3d/

const OUT = {
    qb64: path.join(REPO, 'src/gameplay/spline_path_gen.bi'),
    ts:   path.join(REPO, 'tools/path_editor/src/math/spline_gen.ts'),
};

// ── Emit ──────────────────────────────────────────────────────────────────

const results = {};
for (const ast of splineFrameAsts) {
    const out = emitAll(ast);
    for (const [lang, { source }] of Object.entries(out)) {
        results[lang] = (results[lang] || '') + source + '\n';
    }
}

// ── QB64 output ───────────────────────────────────────────────────────────

const qb64Header = `' spline_path_gen.bi -- AUTO-GENERATED by tools/emit-spline.js
' DO NOT HAND-EDIT.  Source of truth: math/spline-frame.js
' Regenerate: node tools/emit-spline.js
'
' Functions: SpEfMkFrame, SpEfActualPos, SpEfRollFrame, SpEfCrWeights,
'            SpEfCrDerivWeights, SpEfFacingNorm, SpEfArcAdvance
\n`;

fs.writeFileSync(OUT.qb64, qb64Header + results['qb64']);
console.log('QB64 →', path.relative(REPO, OUT.qb64));

// ── TypeScript output ─────────────────────────────────────────────────────

const tsHeader = `// spline_gen.ts -- AUTO-GENERATED by tools/emit-spline.js
// DO NOT HAND-EDIT.  Source of truth: math/spline-frame.js
// Regenerate: node tools/emit-spline.js
//
// Functions: SpEfMkFrame, SpEfActualPos, SpEfRollFrame, SpEfCrWeights,
//            SpEfCrDerivWeights, SpEfFacingNorm, SpEfArcAdvance
\n`;

fs.writeFileSync(OUT.ts, tsHeader + results['ts']);
console.log('TS   →', path.relative(REPO, OUT.ts));

console.log('Done. Regenerated', splineFrameAsts.length, 'functions.');
