#!/usr/bin/env node
// emit-spline.js -- generate QB64 and TypeScript spline math from ExprForge DSL.
//
// SINGLE SOURCE OF TRUTH: all flight-path math lives in math/formula.expr.
// Run this script whenever the math changes. Generated files are committed;
// never hand-edit spline_path_gen.bi or spline_gen.ts.
//
// Usage:  node tools/emit-spline.js
//         (run from the 3d/ repo root)

'use strict';

const fs   = require('fs');
const path = require('path');

const REPO     = path.resolve(__dirname, '..');   // 3d/
const MATH_DIR = path.join(REPO, 'math');

// Resolve exprforge through math/ so it uses the same install regardless of
// where this script is invoked from.
const efPath   = require.resolve('exprforge',      { paths: [MATH_DIR] });
const mathPath = require.resolve('exprforge/math', { paths: [MATH_DIR] });
const ef       = require(efPath);
const math     = require(mathPath);

// ── Session: register exprforge/math helpers as inline-expansion macros ───────

const session = ef.createSession();
session.loadMacro('len3',       math.len3);
session.loadMacro('safeDiv',    math.safeDiv);
session.loadMacro('dot3',       math.dot3);
session.loadMacro('cross3',     math.cross3);
session.loadMacro('normalize3', math.normalize3);

// ── Load .expr file ───────────────────────────────────────────────────────────

const defs = session.loadExpr(path.join(MATH_DIR, 'formula.expr'));

// Emit order must match the order in the old spline-frame.js export so that
// the generated file headers stay stable.
const FN_ORDER = [
    'SpEfMkFrame',
    'SpEfActualPos',
    'SpEfRollFrame',
    'SpEfCrWeights',
    'SpEfCrDerivWeights',
    'SpEfFacingNorm',
    'SpEfArcAdvance',
    'SpEfTransportFrame',
    'SpEfFrustumAtX',
    'SpEfApplyHolonomyCorrection',
    'SpEfMeasureHolonomy',
];

const OUT = {
    qb64: path.join(REPO, 'src/gameplay/spline_path_gen.bi'),
    ts:   path.join(REPO, 'tools/TrailForge/src/math/spline_gen.ts'),
};

// ── Emit (only the two targets we use) ───────────────────────────────────────

const results = { qb64: '', ts: '' };
for (const name of FN_ORDER) {
    const ast = defs[name];
    if (!ast) throw new Error(`formula.expr is missing fn: ${name}`);
    results.qb64 += session.emit(ast, 'qb64').source + '\n';
    results.ts   += session.emit(ast, 'ts').source   + '\n';
}

// ── Function list for headers (auto-derived, never goes stale) ─────────────

function formatFnList(names, linePrefix, indent) {
    const first = `${linePrefix} Functions: `;
    const cont  = `${linePrefix}${' '.repeat(indent)}`;
    let line = first, lines = [];
    for (let i = 0; i < names.length; i++) {
        const sep  = i < names.length - 1 ? ', ' : '';
        const word = names[i] + sep;
        if (line.length + word.length > 79 && line !== first) {
            lines.push(line.trimEnd()); line = cont + word;
        } else {
            line += word;
        }
    }
    lines.push(line.trimEnd());
    return lines.join('\n');
}

// ── QB64 output ───────────────────────────────────────────────────────────────

const qb64Header = `' spline_path_gen.bi -- AUTO-GENERATED by tools/emit-spline.js
' DO NOT HAND-EDIT.  Source of truth: math/formula.expr
' Regenerate: node tools/emit-spline.js
'
${formatFnList(FN_ORDER, "'", 12)}
\n`;

fs.writeFileSync(OUT.qb64, qb64Header + results.qb64);
console.log('QB64 →', path.relative(REPO, OUT.qb64));

// ── TypeScript output ─────────────────────────────────────────────────────────

const tsHeader = `// spline_gen.ts -- AUTO-GENERATED by tools/emit-spline.js
// DO NOT HAND-EDIT.  Source of truth: math/formula.expr
// Regenerate: node tools/emit-spline.js
//
${formatFnList(FN_ORDER, '//', 12)}
\n`;

fs.writeFileSync(OUT.ts, tsHeader + results.ts);
console.log('TS   →', path.relative(REPO, OUT.ts));

console.log('Done. Regenerated', FN_ORDER.length, 'functions.');
