#!/usr/bin/env node
// emit-spline.js -- generate QB64 and TypeScript spline math from exprforge DSL.
//
// SINGLE SOURCE OF TRUTH: all flight-path math lives in exprforge ASTs.
// Run this script whenever the math changes. Generated files are committed;
// never hand-edit spline_path_gen.bi or spline_gen.ts.
//
// Usage:  node tools/emit-spline.js
//         (run from the 3d/ repo root)

'use strict';

const fs   = require('fs');
const path = require('path');

// Load emitAll from exprforge (installed in math/node_modules).
const { emitAll } = require('../math/node_modules/exprforge');

// All spline math ASTs live here — pure JS DSL, no QB64, no TypeScript.
const { splineFrameAsts } = require('../math/spline-frame.js');

const REPO = path.resolve(__dirname, '..');   // 3d/

const OUT = {
    qb64: path.join(REPO, 'src/gameplay/spline_path_gen.bi'),
    ts:   path.join(REPO, 'tools/path_editor/src/math/spline_gen.ts'),
};

// ── Emit ──────────────────────────────────────────────────────────────────

const results = {};
for (const ast of splineFrameAsts) {
    const out = emitAll(ast);
    for (const [lang, { source }] of Object.entries(out)) {
        results[lang] = (results[lang] || '') + source + '\n';
    }
}

// ── Function list for headers (auto-derived, never goes stale) ─────────────

function formatFnList(names, linePrefix, indent) {
    // Wrap at ~80 chars, aligning continuation lines under the first name.
    const first = `${linePrefix} Functions: `;
    const cont  = `${linePrefix}${' '.repeat(indent)}`;
    let line = first, lines = [];
    for (let i = 0; i < names.length; i++) {
        const sep  = i < names.length - 1 ? ', ' : '';
        const word = names[i] + sep;
        if (line.length + word.length > 79 && line !== first) {
            lines.push(line.trimEnd()); line = cont + word;
        } else {
            line += word;
        }
    }
    lines.push(line.trimEnd());
    return lines.join('\n');
}
const fnNames = splineFrameAsts.map(a => a.name);

// ── QB64 output ───────────────────────────────────────────────────────────

const qb64FnList = formatFnList(fnNames, "'", 12);
const qb64Header = `' spline_path_gen.bi -- AUTO-GENERATED by tools/emit-spline.js
' DO NOT HAND-EDIT.  Source of truth: math/spline-frame.js
' Regenerate: node tools/emit-spline.js
'
${qb64FnList}
\n`;

fs.writeFileSync(OUT.qb64, qb64Header + results['qb64']);
console.log('QB64 →', path.relative(REPO, OUT.qb64));

// ── TypeScript output ─────────────────────────────────────────────────────

const tsFnList = formatFnList(fnNames, '//', 12);
const tsHeader = `// spline_gen.ts -- AUTO-GENERATED by tools/emit-spline.js
// DO NOT HAND-EDIT.  Source of truth: math/spline-frame.js
// Regenerate: node tools/emit-spline.js
//
${tsFnList}
\n`;

fs.writeFileSync(OUT.ts, tsHeader + results['ts']);
console.log('TS   →', path.relative(REPO, OUT.ts));

console.log('Done. Regenerated', splineFrameAsts.length, 'functions.');
