#!/usr/bin/env bash
# make-version.sh -- regenerate src/sys/version.bas from VERSION + git state.
#
# Run before every build (wired into tools/buildqb and CI's qb64build.sh) so
# --version, --help, the title/about screens, and telemetry's session_start
# row always reflect the exact commit that produced the binary, instead of a
# hand-edited literal.
#
# VERSION (repo root) is the canonical release version, e.g. "0.1.0".
# A build at that exact tagged commit (git tag vX.Y.Z) with a clean working
# tree embeds the bare "X.Y.Z". Every other build embeds
# "X.Y.Z-dev+<short-sha>" (plus "-dirty" if the working tree has uncommitted
# changes to tracked files).
set -euo pipefail

REPODIR="$(cd "$(dirname "$0")/.." && pwd)"
BASE_VERSION="$(tr -d '[:space:]' < "$REPODIR/VERSION")"

COMMIT="$(git -C "$REPODIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"

DIRTY=""
if [ "$COMMIT" != "unknown" ] && ! git -C "$REPODIR" diff --quiet HEAD -- 2>/dev/null; then
    DIRTY="-dirty"
fi

TAG="$(git -C "$REPODIR" describe --tags --exact-match --match 'v[0-9]*' HEAD 2>/dev/null || true)"

if [ -n "$TAG" ] && [ -z "$DIRTY" ]; then
    VERSION="${TAG#v}"
else
    VERSION="${BASE_VERSION}-dev+${COMMIT}${DIRTY}"
fi

cat > "$REPODIR/src/sys/version.bas" <<EOF
' Auto-generated by tools/make-version.sh -- do not edit
Const VERSION\$ = "$VERSION"
Const BUILD_COMMIT\$ = "$COMMIT"
EOF

echo "==> version: $VERSION"
